LearnToEarn/Learn/Learn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from background_task.models import Task
from LearnToEarn.views import timeLapseRepeat
from accounts.processTasks import process_tasks
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('LearnToEarn.urls')),
    path('', include('accounts.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    # path('admins-dashboard/', include('admins.urls')),
    # path('', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('admins-dashboard/', include('admins.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# process_tasks()
# if not Task.objects.filter(verbose_name="timeLapse").exists():
#     timeLapseRepeat(repeat=1, verbose_name="timeLapse")
#

LearnToEarn/Learn/LearnToEarn/models.py
from django.db import models
from django.core import validators
from accounts.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
import readtime
from django.db.models import Avg


class News(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    heading = models.CharField("Title", max_length=200, null=True, default="Not Updated",
                               validators=[validators.MinLengthValidator(4)])
    content = RichTextUploadingField("Put Your Content Here", null=True, default="Not Updated",
                                     validators=[validators.MinLengthValidator(4)])

    news_pic = models.ImageField("News Pic", max_length=500, upload_to='static/uploads',
                                 default='static/images/newsDefault.jpg')
    date_posted = models.DateTimeField(auto_now_add=True)

    Tags = TaggableManager()

    def __str__(self):
        return self.heading

    def getComments(self):
        comment = Comment.objects.filter(news_id=self.pk).count()
        return comment


class Comment(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    news = models.ForeignKey(News, null=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200, null=True, default="Not Updated",
                               validators=[validators.MinLengthValidator(4)])

    date_commented = models.DateTimeField(auto_now_add=True)


class ContactMessage(models.Model):
    firstname = models.CharField(max_length=100, null=True)
    lastname = models.CharField(max_length=100, null=True)
    email = models.EmailField(null=True)
    phonenumber = models.CharField(max_length=100, null=True)
    subject = models.CharField(max_length=100, null=True)
    query = models.CharField(max_length=1000, null=True)
    date = models.DateField(auto_now_add=True, null=True)
    responded = models.BooleanField(default=False)

    def __str__(self):
        return self.firstname


class Course(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    course_name = models.CharField("Course Name", max_length=200, null=True, default="Not Updated",
                                   )
    course_summary = models.CharField("Course Summary", max_length=200, null=True, default="Not Updated",
                                      )
    to_learn = RichTextField("What students needs to learn before joining this course", max_length=50000, null=True,
                             default="You can join this course right away",
                             )
    course_pic = models.ImageField("Course Pic", max_length=500, upload_to='static/uploads',
                                   default='static/images/slider-01.jpg')
    date = models.DateTimeField(auto_now_add=True, null=True)
    category = TaggableManager()

    def __str__(self):
        return self.course_name

    def getStars(self):
        total = CourseReview.objects.filter(course_id=self.pk).aggregate(Avg('rate'))
        loop = total['rate__avg']
        if loop is not None:
            dec = str(loop - int(loop))[2:]
            if '0' == dec:
                loop = int(loop)
                list = ['', '', '', '', '']
                for i in range(0, loop):
                    list[i] = i
                return list
            else:
                loop = int(loop)
                list = ['', '', '', '', '']
                for i in range(0, loop):
                    list[i] = i
                list[loop] = 'half'
                return list

        else:
            return loop

    def getEnroll(self):
        enrollcount = CourseEnrollement.objects.filter(course_id=self.pk).count()
        return enrollcount

    def getLikes(self):
        likes = CourseLike.objects.filter(course_id=self.pk).count()
        return likes

    def getReview(self):
        count = CourseReview.objects.filter(course_id=self.pk).count()
        return count

    def getModule(self):
        statement = CourseModule.objects.filter(course_id=self.pk).exists()
        return statement

    def Exam(self):
        statement = ExamModel.objects.filter(course_id=self.pk).exists()
        return statement


class CourseEnrollement(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, null=True)
    enrolled = models.BooleanField(default=False)


class CourseLike(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, null=True)
    like = models.BooleanField(default=False)


class CourseModule(models.Model):
    course = models.ForeignKey(Course, null=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, null=True)
    modulenumber = models.IntegerField('Lecture Number', null=True
                                       )
    module = models.CharField('Module Name', max_length=200, null=True,
                              )

    ModuleLecture = RichTextUploadingField('Module Lecture', max_length=50000, null=True,
                                           )

    def __str__(self):
        return self.module

    class Meta:
        ordering = ('modulenumber',)

    def get_readtime(self):
        result = readtime.of_text(self.ModuleLecture)
        return result.text


Rate_Choice = [
    (1, '1-Star'),
    (2, '2-Star'),
    (3, '3-Star'),
    (4, '4-Star'),
    (5, '5-Star'),
]


class CourseReview(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=50000, null=True, default="Not Updated",
                               )
    rate = models.PositiveSmallIntegerField("Choose Your Rating", choices=Rate_Choice)
    edited = models.BooleanField(default=False)
    date_commented = models.DateTimeField(auto_now_add=True)

    def stars(self):
        list = ['', '', '', '', '']
        for i in range(0, self.rate):
            list[i] = i
        return list


class ExamModel(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=True, on_delete=models.CASCADE)
    ExamNumber = models.PositiveSmallIntegerField('Exam Number', null=True
                                                  )
    ExamTitle = models.CharField('Title', max_length=500, null=True, default="Not Updated",
                                 )
    date = models.DateTimeField(auto_now_add=True)

    def MCQ(self):
        statement = ExamQNA.objects.filter(exammodel_id=self.pk).exists()
        return statement

    def ExamQ(self):
        statement = ExamQuestion.objects.filter(exammodel_id=self.pk).exists()
        return statement


class Attempted(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    exammodel = models.ForeignKey(ExamModel, null=True, on_delete=models.CASCADE)
    date_attempted = models.DateTimeField(auto_now_add=True)
    attempted = models.BooleanField(default=False)
    user_score = models.PositiveSmallIntegerField("Score", default=0)


class ExamQNA(models.Model):
    exammodel = models.ForeignKey(ExamModel, null=True, on_delete=models.CASCADE)
    numb = models.PositiveSmallIntegerField("Number", default=0)
    question = models.CharField(max_length=5000, null=True)
    option1 = models.CharField("Option 1", max_length=5000, null=True)
    option2 = models.CharField("Option 2", max_length=5000, null=True)
    option3 = models.CharField("Option 3", max_length=5000, null=True)
    option4 = models.CharField("Option 4", max_length=5000, null=True)
    answer = models.CharField("Answer", max_length=5000, null=True)


class ExamQuestion(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    exammodel = models.OneToOneField(ExamModel, null=True, on_delete=models.CASCADE)
    question = RichTextUploadingField(max_length=5000, default="Paste Your Question in PDF Format HERE", null=True)
    date = models.DateTimeField(auto_now_add=True)


class ExamAnswer(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    examquestion = models.ForeignKey(ExamQuestion, null=True, on_delete=models.CASCADE)
    time = models.PositiveIntegerField(default=600)
    attempted = models.BooleanField(default=False)
    answer = RichTextUploadingField(max_length=5000, default="Paste Your Answer in PDF format here", null=True)
    date = models.DateTimeField(auto_now_add=True)

LearnToEarn/Learn/templates/admins/CreateAdd.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}
<style>
.col-sm-2 {
max-width:400% !important;
}
.help-block {
    display:none;
}
</style>
<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <div class="card py-2 px-2">
    <form class="form" action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form | bootstrap_horizontal }}
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
</div>
{% endblock %}

LearnToEarn/Learn/templates/admins/Response_.html
{% extends 'layout-admin.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}
<style>
.col-lg-2 {
max-width:400% !important;
margin-bottom: 30px;
margin-top:20px;
}
</style>
<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <div class="card py-2 px-2">
    <form class="form" action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form | bootstrap_horizontal }}
        <br>
        <button type="submit" class="btn btn-primary">Submit Your Response</button>
    </form>
    </div>
</div>
{% endblock %}

LearnToEarn/Learn/templates/admins/UpdateMCQ.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}
<style>
.col-sm-2 {
max-width:400% !important;
}
.help-block {
    display:none;
}
</style>
<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <div class="card py-2 px-2">
    <form class="form" action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="row">
          <div class="col">
            <div class="row">
              <div class="col-sm-2">
                  {{form.numb | bootstrap_horizontal}}

              </div>
            </div>
            <div class="row">
              <div class="col-sm-8">
                  {{form.question | bootstrap_horizontal}}
              </div>
            </div>
            <div class="row">
              <div class="col mb-3">
                  {{form.option1 | bootstrap_horizontal}}
              </div>
              <div class="col mb-3">
                  {{form.option2 | bootstrap_horizontal}}
              </div>
            </div>
            <div class="row">
              <div class="col mb-3">
                  {{form.option3 | bootstrap_horizontal}}
              </div>
              <div class="col mb-3">
                  {{form.option4 | bootstrap_horizontal}}
              </div>
            </div>
            <div class="row">
              <div class="col-sm-8">
                  <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2 " for="id_answer">Answer</label>
                    <div class=" col-sm-10 col-lg-10 ">
                        <select name="answer" style="background:url('/static/images/choices.svg') no-repeat right .75rem center; background-size:10px;" class=" form-control" required id="id_answer">
                            <option value selected>----</option>
                            <option id="option1" value="1"></option>
                            <option id="option2" value="2"></option>
                            <option id="option3" value="3"></option>
                            <option id="option4" value="4"></option>
                        </select>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
        <br>
        <button type="submit" class="btn btn-warning">Submit</button>
    </form>
    </div>
</div>

<script>
$( document ).ready(function() {
    $('#option1').val($("#id_option1").val()).text($("#id_option1").val());
    $('#option2').val($("#id_option2").val()).text($("#id_option2").val());
    $('#option3').val($("#id_option3").val()).text($("#id_option3").val());
    $('#option4').val($("#id_option4").val()).text($("#id_option4").val());
    
    $("#id_option1").keyup(function() {
        $('#option1').val($(this).val()).text($(this).val());
    });
    $("#id_option2").keyup(function() {
        $('#option2').val($(this).val()).text($(this).val());
    });
    $("#id_option3").keyup(function() {
        $('#option3').val($(this).val()).text($(this).val());
    });
    $("#id_option4").keyup(function() {
        $('#option4').val($(this).val()).text($(this).val());
    });
});
</script>
{% endblock %}

LearnToEarn/Learn/templates/admins/VRMessages.html
{% extends 'layout-admin.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Query details</li>
    </ol>
    <div class="container">
        <div class=" m-5 border border-4 col-lg-12">

            <p style="text-align:right; ">Date:&nbsp;<b style="color:#ff3498">{{form.date| date:"F d, Y"}}</b></p>
            <br>
            <p style="text-align:center; background-color:#f1fdff;">Subject:&nbsp;<b>{{form.subject}}</b></p>
            <br>
            <p style="margin-bottom:5px;">Hello, &nbsp;<b>{{request.user.username}}</b></p>
            <p style="text-indent:50px; color:#854e85; background-color:#fdfdfd"><b>{{form.query}}</b></p>

            <p>Sincerely,</p>
            <p style="text-indent:50px; text-transform: lowercase; text-transform: capitalize; margin-top:-15px;">{{form.firstname}} {{form.lastname}}</p>
            <br>
            {% if form.responded %}
            <a  href="/admins-dashboard/response/{{form.id}}" style="margin-left:450px;" class="btn btn-info btn-sm disabled">Already Responded</a>
            {% else %}
            <a  href="/admins-dashboard/response/{{form.id}}" style="margin-left:450px;" class="btn btn-info btn-sm">Give Response</a>
            {% endif %}
        </div>
    </div>
</div>
{%endblock%}

LearnToEarn/Learn/templates/admins/addMCQ.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}
<style>
.col-sm-2 {
max-width:400% !important;
}
.help-block {
    display:none;
}
</style>
<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <div class="card py-2 px-2">
    <form class="form" action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="row">
          <div class="col">
            <div class="row">
              <div class="col-sm-2">
                  {{form.numb | bootstrap_horizontal}}

              </div>
            </div>
            <div class="row">
              <div class="col-sm-8">
                  {{form.question | bootstrap_horizontal}}
              </div>
            </div>
            <div class="row">
              <div class="col mb-3">
                  {{form.option1 | bootstrap_horizontal}}
              </div>
              <div class="col mb-3">
                  {{form.option2 | bootstrap_horizontal}}
              </div>
            </div>
            <div class="row">
              <div class="col mb-3">
                  {{form.option3 | bootstrap_horizontal}}
              </div>
              <div class="col mb-3">
                  {{form.option4 | bootstrap_horizontal}}
              </div>
            </div>
            <div class="row">
              <div class="col-sm-8">
                  <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2 " for="id_answer">Answer</label>
                    <div class=" col-sm-10 col-lg-10 ">
                        <select name="answer" style="background:url('/static/images/choices.svg') no-repeat right .75rem center; background-size:10px;" class=" form-control" required id="id_answer">
                            <option value selected>----</option>
                            <option id="option1" value="1"></option>
                            <option id="option2" value="2"></option>
                            <option id="option3" value="3"></option>
                            <option id="option4" value="4"></option>
                        </select>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
</div>

<script>
$( document ).ready(function() {
    $('#option1').val($("#id_option1").val()).text($("#id_option1").val());
    $('#option2').val($("#id_option2").val()).text($("#id_option2").val());
    $('#option3').val($("#id_option3").val()).text($("#id_option3").val());
    $('#option4').val($("#id_option4").val()).text($("#id_option4").val());

    $("#id_option1").keyup(function() {
        $('#option1').val($(this).val()).text($(this).val());
    });
    $("#id_option2").keyup(function() {
        $('#option2').val($(this).val()).text($(this).val());
    });
    $("#id_option3").keyup(function() {
        $('#option3').val($(this).val()).text($(this).val());
    });
    $("#id_option4").keyup(function() {
        $('#option4').val($(this).val()).text($(this).val());
    });
});
</script>
{% endblock %}

LearnToEarn/Learn/templates/admins/allCourses.html
{% extends 'layout-admin.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}
<style>
.btn-v{
    width:120px
}
.btn-s{
    width:100px
}
</style>

<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <div style="margin-top:3rem; margin-bottom:3rem">
      <a href="/admins-dashboard/CourseCreate" class="btn btn-primary">Add New Course</a>
         <div class="card mb-4" style="margin-top:3rem; margin-right:3rem;">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Total News : {{courses.count}}
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Course Name</th>
                            <th>Date Added</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for i in courses  %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><a href="/courses/courseDesk/{{i.id}}">{{i.course_name}}</a></td>
                            <td>{{i.date| date:"F d, Y"}}</td>
                            {% if user.id == i.user_id %}
                            <td>
                              <a href="/admins-dashboard/editCourse/{{i.id}}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit</a>
                              <a href="/admins-dashboard/delCourse/{{i.id}}"  class="btn btn-danger btn-sm" onclick="return confirm('Want to delete?')"><i class="fa fa-trash"></i> Delete</a>
                                {% if i.getModule %}
                                    <a href="/admins-dashboard/allModules/{{i.id}}" class="btn btn-v btn-primary btn-sm">View Module</a>
                                {% else %}
                                    <a href="/admins-dashboard/addModule/{{i.id}}" class="btn btn-v btn-primary btn-sm">Create Module</a>
                                {% endif %}
                                {% if i.Exam %}
                                  <a href="/admins-dashboard/allExams/{{i.id}}" class="btn btn-primary btn-s btn-sm">View Exam</a>
                                {% else %}
                                  <a href="/admins-dashboard/examCreate/{{i.id}}" class="btn btn-primary btn-s btn-sm">Create Exam</a>
                                {% endif %}
                            </td>
                            {% else %}
                            <td>
                              <a href="/admins-dashboard/editCourse/{{i.id}}" class="disabled btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit</a>
                              <a href="/admins-dashboard/delCourse/{{i.id}}" class="disabled btn btn-danger btn-sm" onclick="return confirm('Want to delete?')"><i class="fa fa-trash"></i> Delete</a>
                                <span>You don't have permission</span>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
         </div>
    </div>
</div>

{%endblock%}

LearnToEarn/Learn/templates/admins/allModules.html
{% extends 'layout-admin.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}

<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <div style="margin-top:3rem; margin-bottom:3rem">
      <a href="/admins-dashboard/addModule/{{course_id}}" class="btn btn-primary">Add Module</a>
         <div class="card mb-4" style="margin-top:3rem; margin-right:3rem;">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Total News : {{modules.count}}
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Module No.</th>
                            <th>Module Name</th>
                            <th>Date Added</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for i in modules  %}
                        <tr>
                            <td>{{i.modulenumber}}</td>
                            <td>{{i.module}}</td>
                            <td>{{i.date| date:"F d, Y"}}</td>
                            <td>
                              <a href="/admins-dashboard/editModule/{{course_id}}/{{i.id}}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit</a>
                              <a href="/admins-dashboard/delModule/{{course_id}}/{{i.id}}" class="btn btn-danger btn-sm" onclick="return confirm('Want to delete?')"><i class="fa fa-trash"></i> Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
         </div>
    </div>
</div>

{%endblock%}

LearnToEarn/Learn/templates/admins/allNews.html
{% extends 'layout-admin.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <div style="margin-top:3rem; margin-bottom:3rem">
      <a href="/admins-dashboard/newsPost" class="btn btn-primary">Add News</a>
         <div class="card mb-4" style="margin-top:3rem; margin-right:3rem;">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Total News : {{news.count}}
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Heading</th>
                            <th>Date Published</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for i in news  %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><a href="/newsPortal/{{i.id}}">{{i.heading}}</a></td>
                            <td>{{i.date_posted| date:"F d, Y"}}</td>
                            <td>
                              <a href="/admins-dashboard/editNewsPost/{{i.id}}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit</a>
                              <a href="/admins-dashboard/delNewsPost/{{i.id}}" class="btn btn-danger btn-sm" onclick="return confirm('Want to delete?')"><i class="fa fa-trash"></i> Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
         </div>
    </div>
</div>

{%endblock%}

LearnToEarn/Learn/templates/admins/allQNA.html
{% extends 'layout-admin.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}

<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <div style="margin-top:3rem; margin-bottom:3rem">
      <a href="/admins-dashboard/qnaCreate/{{exam_id}}" class="btn btn-primary">Add MCQ</a>
         <div class="card mb-4" style="margin-top:3rem; margin-right:3rem;">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Total News : {{total.count}}
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Question No.</th>
                            <th>Question</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for i in total  %}
                        <tr>
                            <td>{{i.numb}}</td>
                            <td>{{i.question}}</td>
                            <td>
                              <a href="/admins-dashboard/editQNA/{{exam_id}}/{{i.id}}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit</a>
                              <a href="/admins-dashboard/delQNA/{{exam_id}}/{{i.id}}" class="btn btn-danger btn-sm" onclick="return confirm('Want to delete?')"><i class="fa fa-trash"></i> Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
         </div>
    </div>
</div>

{%endblock%}

LearnToEarn/Learn/templates/admins/allSubmittedAnswers.html
{% extends 'layout-admin.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}
<style>
.btn-v{
    width:150px
}
.btn-s{
    width:100px
}
</style>
<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <div style="margin-top:3rem; margin-bottom:3rem">
         <div class="card mb-4" style="margin-top:3rem; margin-right:3rem;">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Total News : {{answers.count}}
            </div>
            <div class="card-body">
                <table class="table table-hover" id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Sn.</th>
                            <th>Answers</th>
                            <th>Date Submitted</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for i in answers  %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{i.answer}}</td>
                            <td>{{i.date}}</td>
                            <td>
                              <a href="/admins-dashboard/editExam/{{course_id}}/{{i.id}}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Give Marks</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
         </div>
    </div>
</div>

{%endblock%}

LearnToEarn/Learn/templates/admins/editNewsPost.html
{% extends 'layout-admin.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap %}
{% block title %}
    <title>Learn To Earn</title>
{% endblock%}
{% block content %}
<div id="layoutSidenav">
    {% include 'navbar-admin.html' %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Dashboard</h1>
                <div class="card py-2 px-2">
                <form class="form" action="" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form | bootstrap_horizontal }}
                    <br>
                    <button type="submit" class="btn btn-warning">Update</button>
                </form>
                </div>
            </div>
        </main>
        {% include 'footer-admin.html' %}
    </div>
</div>
{% endblock %}